### ISSUE TITLE
`\acuse` doesn't work for a csv-list of acronyms

### ISSUE THREAD

**Issue by Skillmon** [cgnieder/acro#174] opened 2020-08-17 20:05 UTC
`acro` used to parse a list of acronyms inside the argument of `\acuse` correctly, but in the recent version, it doesn't iterate over the list but instead uses the argument as a single acronym in any case. See the following MWE:

```tex
\documentclass[]{article}

\usepackage{acro}
\DeclareAcronym{abc}
  {
    ,short=ABC
    ,long=alphabet
  }
\DeclareAcronym{wine}
  {
    ,short=Wine
    ,long=Wine Is Not an Emulator
  }

\begin{document}
\acuse{abc,wine}
\end{document}
```

The package will try to build the macro name `g__acro_abc,wine_int` and increment it, which will fail.

**Comment by cgnieder** [comment] 2020-08-17 20:58
This is a duplicate of issue #166

**Closed** 2020-08-17 20:58 UTC
